### ISSUE TITLE
Environment variable instructions in Readme

### ISSUE THREAD

**Issue by dpaolella** [spatialmodel/inmap#10]
The Readme only has directions to define the evaldata environment variable in the section that describes how to compile InMAP. Won't users need to define the evaldata environment variable regardless of whether they compile? Alternatively they could just replace "${evaldata}" in the config file with the absolute path for the evaldata folder. Either way, we may want to clarify this step.

**Comment by ctessum** [comment]
Makes sense. Would you be willing to fix this documentation?

**Comment by dpaolella** [comment]
Fixed as of most recent update to master.
