### ISSUE TITLE
evaldata mortality rates are from 2005

### ISSUE THREAD

**Issue by ctessum** [spatialmodel/inmap#11]
We should include more recent data in the next release.

**Comment by dpaolella** [comment]
This involves uploading new eval data to zenodo right?

**Comment by ctessum** [comment]
Yes. We can do it at the same time we release the new version of the model

**Comment by dpaolella** [comment]
Is there some documentation that explains which age groups are covered by the mortality data? I can't remember whether it is adult-only or all ages.

**Comment by ctessum** [comment]
Fixed in v1.3
