### ISSUE TITLE
Output projection is hard coded

### ISSUE THREAD

**Issue by ctessum** [spatialmodel/inmap#4]
Currently, the spatial projection for the output file is set as a constant. This will cause a problem for versions of the model that do not use that specific projection.

**Comment by dpaolella** [comment]
Are future versions of the model likely to be using different spatial projections? Or is the goal to have the spatial projection of the output file chosen based on the spatial projection of the inputs?

**Comment by ctessum** [comment]
The current version of the model uses a Lambert conic conformal projection, which will not work if we want to create a global version of the model because the whole globe cannot be projected onto a cone.

The model is already able to use different spatial projections, however. The problem is that the projection ".prj file" of the output file is only correct when the default projection is being used. The reason for this is that the spatial reprojection library that inmap uses (https://github.com/ctessum/geom/tree/master/proj) is not able to create ".prj" files. So the main work involved in fixing this issue is to add that capability to the reprojection library.

**Comment by ctessum** [comment]
Fixed for now in 4821d31
